// <auto-generated/>
using System;
using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace Xhttp;

/// <summary>
/// Indicates that the marked type should be processed by xhttp as a HTTP client
/// to be generated.
/// </summary>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Interface, Inherited = false)]
internal sealed class ClientAttribute : Attribute;
