// <auto-generated/>
#pragma warning disable
using System;
using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace Xhttp;

/// <summary>
/// Indicates this method is for a HEAD HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"HEAD"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class HeadAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a GET HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"GET"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class GetAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a POST HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"POST"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class PostAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a PUT HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"PUT"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class PutAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a PATCH HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"PATCH"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class PatchAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a DELETE HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"DELETE"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class DeleteAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for a OPTIONS HTTP request to the provided
/// <paramref name="route"/>.
/// </summary>
/// <remarks>
/// This is equivalent to using the <see cref="RequestAttribute"/> with the
/// first parameter as <code>"OPTIONS"</code>.
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class OptionsAttribute(string route) : Attribute;

/// <summary>
/// Indicates this method is for an HTTP request to the provided
/// <paramref name="route"/> with the provided <paramref name="method"/>.
/// </summary>
/// <remarks>
/// <para>
///     A few attributes for common HTTP methods are already provided for
///     convenience.
/// </para>
/// <para>
///     For HEAD use <see cref="HeadAttribute"/>,
///     for GET use <see cref="GetAttribute"/>,
///     for POST use <see cref="PostAttribute"/>,
///     for DELETE use <see cref="DeleteAttribute"/>,
///     for PUT use <see cref="PutAttribute"/>,
///     for PATCH use <see cref="PatchAttribute"/>
///     and for OPTIONS use <see cref="OptionsAttribute"/>.
/// </para>
/// </remarks>
/// <param name="route">
/// The route the request should be made to. <b>SHOULD NOT</b> start with a
/// slash.
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
internal sealed class RequestAttribute(string method, string route) : Attribute;

/// <summary>
/// A set of headers to add to the request being sent.
/// </summary>
/// <param name="headers">
/// Headers in the <code>NAME: VALUE</code> format. Both sides of the template
/// will be trimmed before being added (<code>HEADER:VALUE</code> is equivalent
/// to <code>HEADER : VALUE</code>).
/// </param>
[Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Interface | AttributeTargets.Method, AllowMultiple = true)]
internal sealed class HeadersAttribute(params string[] headers) : Attribute;

/// <summary>
/// The formatting mode that should be applied to query parameters for this
/// request.
/// </summary>
/// <param name="uriFormat"></param>
// [Embedded, Conditional("XHTTP_KEEP_ATTRIBUTES"), AttributeUsage(AttributeTargets.Method)]
// public class QueryUriFormatAttribute(UriFormat format) : Attribute;
