// <auto-generated />

using System.CodeDom.Compiler;

namespace TypedHttp;

// WARN: DO NOT REMOVE THE `x-release-please-...` COMMENTS NOR MOVE THEM TO ANOTHER LINE
//       RELEASE-PLEASE DOES REPLACING ON THE LINE THE COMMENT IS ON SO IF IT'S MISSING
//       OR ELSEWHERE, THIS WILL NOT BE UPDATED AND MESS UP OUR CODE GENERATION.
internal static class ThisVersion
{
    public const string Version     = "0.1.0";      // x-release-please-version
    public const int    Major       = 0;            // x-release-please-major
    public const int    Minor       = 1;            // x-release-please-minor
    public const int    Patch       = 0;            // x-release-please-patch
    public const string ReleaseDate = "2026-04-18"; // x-release-please-date
}
