using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests;

public class HttpMethodTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesGetRequestsCorrectly()
    {
        const string source =
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("auth/user")]
                Task<string> FetchUser(string a);
            }
            """;
        const string expectedOutput =
            """
            // <auto-generated/>

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = new global::System.Text.Json.JsonSerializerOptions(global::System.Text.Json.JsonSerializerDefaults.Web);
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public global::System.Threading.Tasks.Task<string> FetchUser(string a)
                    {
                        var ___routeBuilder = new global::System.Text.StringBuilder("auth/user");
                        ___routeBuilder.Append('?');
                        if (a is not null) ___routeBuilder.Append($"a={(global::System.Web.HttpUtility.UrlEncode(a.ToString()))}&");
                        var ___route = ___routeBuilder.ToString(0, ___routeBuilder.Length - 1);

                        using var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route);



                        throw new global::System.NotImplementedException();
                    }
                }
            }

            """;

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
