using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace Xhttp.Tests;

public class TestBase
{
    private static Assembly s_generatorAssembly = typeof(HttpClientGenerator).Assembly;

    protected static Task TestGenerator(string inputSource, (string filename, string content) expectedOutput)
    {
        var test = new CSharpSourceGeneratorTest<HttpClientGenerator, DefaultVerifier>();
#if NET8_0
        test.ReferenceAssemblies = ReferenceAssemblies.Net.Net80;
#elif NET10_0
        test.ReferenceAssemblies = ReferenceAssemblies.Net.Net100;
#endif
        test.TestCode             = inputSource;
        test.TestState.OutputKind = OutputKind.DynamicallyLinkedLibrary;
        test.TestState.GeneratedSources.Add((typeof(HttpClientGenerator), "Microsoft.CodeAnalysis.EmbeddedAttribute.cs",
                                             """
                                                 // <auto-generated/>
                                                 namespace Microsoft.CodeAnalysis
                                                 {
                                                     internal sealed partial class EmbeddedAttribute : global::System.Attribute
                                                     {
                                                     }
                                                 }
                                                 """.ReplaceLineEndings("\r\n")));
        test.TestState.GeneratedSources.Add((typeof(HttpClientGenerator), "ClientAttributes.cs",
                                             GetEmbeddedText("ClientAttributes.cs")));
        test.TestState.GeneratedSources.Add((typeof(HttpClientGenerator), "RequestAttributes.cs",
                                             GetEmbeddedText("RequestAttributes.cs")));
        test.TestState.GeneratedSources.Add((typeof(HttpClientGenerator), "ParameterAttributes.cs",
                                             GetEmbeddedText("ParameterAttributes.cs")));
        test.TestState.GeneratedSources.Add((typeof(HttpClientGenerator), expectedOutput.filename,
                                             expectedOutput.content));
        return test.RunAsync(TestContext.Current.CancellationToken);
    }

    private static string GetEmbeddedText(string path)
    {
        using var stream = s_generatorAssembly.GetManifestResourceStream(path)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
