using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Xhttp.Model;

namespace Xhttp;

public partial class HttpClientGenerator
{
    private static partial class Writer
    {
        private const string HttpClientField  = "___httpClient";
        private const string JsonOptionsField = "___jsonOptions";

        public static partial SourceText WriteClient(
            Client            client,
            CancellationToken cancellationToken)
        {
            var       interfaceName = client.Name;
            var       className     = client.Name.Substring(1);
            using var stringWriter  = new StringWriter();
            using var writer        = new IndentedTextWriter(stringWriter);

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLineNoTabs("");

            foreach (var container in client.Containers)
            {
                cancellationToken.ThrowIfCancellationRequested();
                writer.WriteLine(container);
                writer.WriteLine("{");
                writer.Indent++;
            }

            writer.WriteLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Xhttp\", \"0.1.0\")]");
            writer.WriteLine($"{client.Modifiers} sealed class {className} : {interfaceName}");
            writer.WriteLine("{");
            writer.Indent++;

            WritePreamble(writer, className);

            foreach (var request in client.Requests)
            {
                WriteRequest(writer,
                             client.Headers.Array,
                             request,
                             cancellationToken);
            }

            writer.Indent--;
            writer.WriteLine("}");

            for (var count = 0; count < client.Containers.Count; count++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                writer.Indent--;
                writer.WriteLine("}");
            }

            return SourceText.From(stringWriter.ToString(), Encoding.UTF8);
        }

        private static void WritePreamble(
            IndentedTextWriter writer,
            string             name)
        {
            writer.WriteLine($"private readonly {Types.HttpClient} {HttpClientField};");
            writer.WriteLine($"private readonly {Types.JsonSerializerOptions} {JsonOptionsField};");
            writer.WriteLineNoTabs("");
            writer.WriteLine($"public {name}({Types.HttpClient} httpClient)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"this.{HttpClientField} = httpClient;");
            writer.WriteLine(
                $"this.{JsonOptionsField} = new {Types.JsonSerializerOptions}({Types.JsonSerializerDefaults}.Web);");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLineNoTabs("");
            writer.WriteLine(
                $"public {name}({Types.HttpClient} httpClient, {Types.JsonSerializerOptions} jsonOptions)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"this.{HttpClientField} = httpClient;");
            writer.WriteLine($"this.{JsonOptionsField} = jsonOptions;");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteTemplate(
            IndentedTextWriter    writer,
            Template              template,
            Func<string, string>? interpolationTransform = null)
        {
            interpolationTransform ??= static x => x;
            if (template.Parts.Length == 1)
            {
                if (template.Parts[0].Kind == TemplatePartKind.String)
                {
                    writer.Write(SymbolDisplay.FormatLiteral(template.Parts[0].Value,
                                                             quote: true));
                }
                else
                {
                    writer.Write("$\"{");
                    writer.Write(interpolationTransform(template.Parts[0].Value)!);
                    writer.Write("}\"");
                }
            }
            else
            {
                writer.Write("$\"");
                foreach (var part in template.Parts)
                {
                    if (part.Kind == TemplatePartKind.String)
                    {
                        writer.Write(SymbolDisplay.FormatLiteral(part.Value,
                                                                 quote: false));
                    }
                    else
                    {
                        writer.Write('{');
                        writer.Write(interpolationTransform(part.Value)!);
                        writer.Write('}');
                    }
                }

                writer.Write('"');
            }
        }

        private static class Types
        {
            public const string HttpClient             = "global::System.Net.Http.HttpClient";
            public const string JsonSerializerDefaults = "global::System.Text.Json.JsonSerializerDefaults";
            public const string JsonSerializerOptions  = "global::System.Text.Json.JsonSerializerOptions";
            public const string Task                   = "global::System.Threading.Tasks.Task";
            public const string HttpRequestMessage     = "global::System.Net.Http.HttpRequestMessage";
            public const string HttpMethod             = "global::System.Net.Http.HttpMethod";
            public const string StringBuilder          = "global::System.Text.StringBuilder";
            public const string HttpUtility            = "global::System.Web.HttpUtility";
        }
    }
}
