using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Features.HttpMethods;

public class PutTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesPutRequestsCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Put("items")]
                Task UpdateItem();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task UpdateItem()
                      {
                          var ___route = "items";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Put, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
