using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace TypedHttp.Tests;

public class TestBase
{
    private static readonly Assembly s_generatorAssembly = typeof(HttpClientGenerator).Assembly;

    protected static string CSharp([StringSyntax("C#")] string code) { return code; }

    protected static Task TestGenerator(
        string                          inputSource,
        (string filename, string content) expectedOutput,
        bool                            referenceCommon = false)
    {
        var test = CreateTest(inputSource, referenceCommon);
        test.TestState.GeneratedSources.Add(
            (typeof(HttpClientGenerator), expectedOutput.filename, expectedOutput.content));
        return test.RunAsync(TestContext.Current.CancellationToken);
    }

    /// <summary>
    /// Runs the generator against source that is expected to produce one or more diagnostics
    /// (and therefore no client output). Diagnostic locations are declared inline with the
    /// testing library's numbered <c>{|#N:span|}</c> markup and matched to the supplied
    /// <see cref="DiagnosticResult"/>s via <see cref="DiagnosticResult.WithLocation(int)"/>, so
    /// each diagnostic's id, severity, location <em>and</em> message arguments are verified. When
    /// the generator reports any diagnostic it skips emission, so only the post-initialization
    /// attribute sources are expected to be generated.
    /// </summary>
    protected static Task TestDiagnostics(
        [StringSyntax("C#")] string inputSource,
        params DiagnosticResult[]   expected)
    {
        var test = CreateTest(inputSource, referenceCommon: false);
        test.TestState.ExpectedDiagnostics.AddRange(expected);
        return test.RunAsync(TestContext.Current.CancellationToken);
    }

    private static CSharpSourceGeneratorTest<HttpClientGenerator, DefaultVerifier> CreateTest(
        string inputSource,
        bool   referenceCommon)
    {
        var test = new CSharpSourceGeneratorTest<HttpClientGenerator, DefaultVerifier>();
#if NET8_0
        test.ReferenceAssemblies = ReferenceAssemblies.Net.Net80;
#elif NET9_0
        test.ReferenceAssemblies = ReferenceAssemblies.Net.Net90;
#elif NET10_0 || NET11_0
        test.ReferenceAssemblies = ReferenceAssemblies.Net.Net100;
#endif
        test.TestCode             = inputSource;
        test.TestState.OutputKind = OutputKind.DynamicallyLinkedLibrary;
        // Only referenced by tests that actually need TypedHttp.Response/Response<T> to resolve.
        // Left out by default so the rest of the suite keeps covering the case where a consumer
        // hasn't referenced TypedHttp.Common at all - the generator must not crash for those.
        if (referenceCommon)
            test.TestState.AdditionalReferences.Add(typeof(Response).Assembly);
        test.TestState.GeneratedSources.Add(
            (typeof(HttpClientGenerator), "Microsoft.CodeAnalysis.EmbeddedAttribute.cs",
             """
                 // <auto-generated/>
                 namespace Microsoft.CodeAnalysis
                 {
                     internal sealed partial class EmbeddedAttribute : global::System.Attribute
                     {
                     }
                 }
                 """.ReplaceLineEndings("\r\n")));
        test.TestState.GeneratedSources.Add(
            (typeof(HttpClientGenerator), "ClientAttributes.cs", GetEmbeddedText("ClientAttributes.cs")));
        test.TestState.GeneratedSources.Add(
            (typeof(HttpClientGenerator), "RequestAttributes.cs", GetEmbeddedText("RequestAttributes.cs")));
        test.TestState.GeneratedSources.Add(
            (typeof(HttpClientGenerator), "ParameterAttributes.cs", GetEmbeddedText("ParameterAttributes.cs")));
        return test;
    }

    private static string GetEmbeddedText(string path)
    {
        using var stream = s_generatorAssembly.GetManifestResourceStream(path)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
