using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.ReturnTypes;

public class CustomJsonReturnTypeTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesCustomJsonReturnTypeCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("users")]
                Task<User> GetUser();
            }

            public class User { }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<global::X.User> GetUser()
                      {
                          var ___route = "users";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  if (this.___jsonContext is not null)
                                  {
                                      return await ___response.Content.ReadFromJsonAsync<global::X.User>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      return await ___response.Content.ReadFromJsonAsync<global::X.User>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      return await ___response.Content.ReadFromJsonAsync<global::X.User>().ConfigureAwait(false);
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
