using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Features.ReturnTypes;

public class ResponseOfTReturnTypeTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesResponseOfTReturnTypeCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("users")]
                Task<Response<User>> GetUser();
            }

            public class User { }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<global::TypedHttp.Response<global::X.User>> GetUser()
                      {
                          var ___route = "users";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  global::X.User ___deserializedJson = default!;
                                  if (___response.IsSuccessStatusCode)
                                  {
                                      if (this.___jsonContext is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User))).ConfigureAwait(false);
                                      }
                                      else if (this.___jsonOptions is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>(this.___jsonOptions).ConfigureAwait(false);
                                      }
                                      else
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>().ConfigureAwait(false);
                                      }
                                  }
                                  return global::TypedHttp.Response<global::X.User>.FromMessage(___response, ___deserializedJson);
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput), referenceCommon: true);
    }

    [Fact]
    public async Task Generator_GeneratesValueTaskOfResponseOfTReturnTypeCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("users")]
                ValueTask<Response<User>> GetUser();
            }

            public class User { }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.ValueTask<global::TypedHttp.Response<global::X.User>> GetUser()
                      {
                          var ___route = "users";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  global::X.User ___deserializedJson = default!;
                                  if (___response.IsSuccessStatusCode)
                                  {
                                      if (this.___jsonContext is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User))).ConfigureAwait(false);
                                      }
                                      else if (this.___jsonOptions is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>(this.___jsonOptions).ConfigureAwait(false);
                                      }
                                      else
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>().ConfigureAwait(false);
                                      }
                                  }
                                  return global::TypedHttp.Response<global::X.User>.FromMessage(___response, ___deserializedJson);
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput), referenceCommon: true);
    }
}
