using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Parameters;

public class AuthorizeParameterTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesAuthorizeParameterWithBearerCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("profile")]
                Task<string> GetProfile([Authorize] string token);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetProfile(string token)
                    {
                        var ___route = "profile";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            ___request.Headers.Add("Authorization", $"Bearer {token}");
                            using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesAuthorizeParameterWithCustomSchemeCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("data")]
                Task<string> GetData([Authorize("ApiKey")] string key);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetData(string key)
                    {
                        var ___route = "data";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            ___request.Headers.Add("Authorization", $"ApiKey {key}");
                            using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
