using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Parameters;

public class BodyParametersTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesJsonBodyParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("users")]
                Task CreateUser([Body] User user);
            }

            public class User { }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task CreateUser(global::X.User user)
                    {
                        var ___route = "users";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                        {
                            global::System.Net.Http.HttpContent ___httpContent;
                            if (this.___jsonContext is not null)
                            {
                                ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User)));
                            }
                            else
                            {
                                ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, options: this.___jsonOptions);
                            }
                            using (___httpContent)
                            {
                                ___request.Content = ___httpContent;
                                using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                {
                                    ___response.EnsureSuccessStatusCode();
                                }
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesStringBodyParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("log")]
                Task LogMessage([Body] string message);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task LogMessage(string message)
                    {
                        var ___route = "log";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                        {
                            global::System.Net.Http.HttpContent ___httpContent;
                            using (___httpContent = new global::System.Net.Http.ByteArrayContent(global::System.Text.Encoding.UTF8.GetBytes(message)))
                            {
                                ___request.Content = ___httpContent;
                                using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                {
                                    ___response.EnsureSuccessStatusCode();
                                }
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesHttpContentBodyParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Net.Http;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("upload")]
                Task Upload([Body] HttpContent content);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task Upload(global::System.Net.Http.HttpContent content)
                    {
                        var ___route = "upload";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                        {
                            global::System.Net.Http.HttpContent ___httpContent;
                            ___httpContent = content;
                            ___request.Content = ___httpContent;
                            using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesStreamBodyParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.IO;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("stream")]
                Task PostStream([Body] Stream stream);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task PostStream(global::System.IO.Stream stream)
                    {
                        var ___route = "stream";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                        {
                            global::System.Net.Http.HttpContent ___httpContent;
                            using (___httpContent = new global::System.Net.Http.StreamContent(stream))
                            {
                                ___request.Content = ___httpContent;
                                using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                {
                                    ___response.EnsureSuccessStatusCode();
                                }
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
