using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Parameters;

public class CancellationTokenTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesCancellationTokenParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("data")]
                Task<string> GetData(CancellationToken cancellationToken);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetData(global::System.Threading.CancellationToken cancellationToken)
                    {
                        var ___route = "data";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesCancellationTokenWithRouteParameterCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items/{id}")]
                Task<string> GetItem(string id, CancellationToken cancellationToken);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetItem(string id, global::System.Threading.CancellationToken cancellationToken)
                    {
                        var ___route = $"items/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
