using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Parameters;

public class ParameterCombinationsTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesRouteAndQueryParametersCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("users/{id}")]
                Task<string> GetUserPosts(string id, string filter);
            }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetUserPosts(string id, string filter)
                    {
                        var ___routeBuilder = new global::System.Text.StringBuilder($"users/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}");
                        ___routeBuilder.Append('?');
                        if (filter is not null) ___routeBuilder.Append($"filter={(global::System.Web.HttpUtility.UrlEncode(filter.ToString()))}&");
                        var ___route = ___routeBuilder.ToString(0, ___routeBuilder.Length - 1);
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesRouteBodyAndHeaderParametersCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("users/{id}")]
                Task UpdateUser(string id, [Body] User user, [Header("X-Request-Id")] string requestId);
            }

            public class User { }
            """);
        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task UpdateUser(string id, global::X.User user, string requestId)
                    {
                        var ___route = $"users/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                        {
                            ___request.Headers.Add("X-Request-Id", $"{requestId}");
                            global::System.Net.Http.HttpContent ___httpContent;
                            if (this.___jsonContext is not null)
                            {
                                ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User)));
                            }
                            else
                            {
                                ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, options: this.___jsonOptions);
                            }
                            using (___httpContent)
                            {
                                ___request.Content = ___httpContent;
                                using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                {
                                    ___response.EnsureSuccessStatusCode();
                                }
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
