using System.CodeDom.Compiler;
using Xhttp.Model;

namespace Xhttp.IO;

internal sealed class ClientWriter(IndentedTextWriter writer) : BaseWriter(writer)
{
    private readonly RequestWriter _requestWriter = new(writer);

    public void WriteClient(
        Client            client,
        CancellationToken cancellationToken = default)
    {
        var interfaceName = client.Name;
        var className     = client.Name.Substring(1);

        Writer.WriteLine("// <auto-generated/>");
        Writer.WriteLine("using System.Net.Http.Json;");
        Writer.WriteLineNoTabs("");

        foreach (var container in client.Containers)
        {
            cancellationToken.ThrowIfCancellationRequested();
            Writer.WriteLine(container);
            Writer.WriteLine("{");
            Writer.Indent++;
        }

        Writer.WriteLine($"// Generated by xhttp {ThisVersion.Version} released on {ThisVersion.ReleaseDate}");
        Writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Xhttp\", \"{ThisVersion.Version}\")]");
        Writer.WriteLine($"{client.Modifiers} sealed class {className} : {interfaceName}");
        Writer.WriteLine("{");
        Writer.Indent++;

        WritePreamble(className);

        foreach (var request in client.Requests)
        {
            _requestWriter.WriteRequest(client.Headers.Array,
                                        request,
                                        cancellationToken);
        }

        Writer.Indent--;
        Writer.WriteLine("}");

        for (var count = 0; count < client.Containers.Count; count++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            Writer.Indent--;
            Writer.WriteLine("}");
        }
    }

    private void WritePreamble(string name)
    {
        Writer.WriteLine($"private readonly {Types.HttpClient} {Names.HttpClientField};");
        Writer.WriteLine($"private readonly {Types.JsonSerializerOptions} {Names.JsonOptionsField};");
        Writer.WriteLine($"private readonly {Types.JsonSerializerContext} {Names.JsonContextField};");
        Writer.WriteLineNoTabs("");
        Writer.WriteLine($"public {name}({Types.HttpClient} httpClient)");
        Writer.WriteLine("{");
        Writer.Indent++;
        Writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
        Writer.Indent--;
        Writer.WriteLine("}");
        Writer.WriteLineNoTabs("");
        Writer.WriteLine($"public {name}({Types.HttpClient} httpClient, {Types.JsonSerializerOptions} jsonOptions)");
        Writer.WriteLine("{");
        Writer.Indent++;
        Writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
        Writer.WriteLine($"this.{Names.JsonOptionsField} = jsonOptions;");
        Writer.Indent--;
        Writer.WriteLine("}");
        Writer.WriteLineNoTabs("");
        Writer.WriteLine($"public {name}({Types.HttpClient} httpClient, {Types.JsonSerializerContext} jsonContext)");
        Writer.WriteLine("{");
        Writer.Indent++;
        Writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
        Writer.WriteLine($"this.{Names.JsonContextField} = jsonContext;");
        Writer.Indent--;
        Writer.WriteLine("}");
    }
}
