using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Features.Templates;

public class BraceEscapeTests : TestBase
{
    // Regression: a route that is a pure literal (no {param} hole) containing escaped braces
    // ({{ / }}) must collapse them to single braces at runtime. The parser keeps them doubled
    // for the interpolated ($"...") path, so the lone-literal fast path has to un-double them -
    // otherwise the emitted "items/{{literal}}" would reach the server with doubled braces.
    [Fact]
    public async Task Generator_EscapedBracesInLiteralRouteAreUndoubled()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items/{{literal}}")]
                Task<string> GetItems();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<string> GetItems()
                      {
                          var ___route = "items/{literal}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  #if NET5_0_OR_GREATER
                                  return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                                  #else
                                  return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                                  #endif
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    // Guards the other branch: when an escaped brace shares a template with a real {param} hole,
    // the multi-part interpolated ($"...") path must keep the braces doubled so C# string
    // interpolation collapses them at runtime (a bare "{" there would be a compile error).
    [Fact]
    public async Task Generator_EscapedBracesAlongsideParameterStayDoubled()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items/{{x}}/{id}")]
                Task<string> GetItem(int id);
            }
            """);
        var expectedOutput = CSharp(
            $$$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{{ThisVersion.Version}}} released on {{{ThisVersion.ReleaseDate}}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{{ThisVersion.Version}}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<string> GetItem(int id)
                      {
                          var ___route = $"items/{{x}}/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  #if NET5_0_OR_GREATER
                                  return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                                  #else
                                  return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                                  #endif
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
