using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Headers;

public class HeaderInteractionTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesClientAndRequestHeadersTogetherCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            [Headers("X-Client: client-value")]
            public interface ICustomClient
            {
                [Get("data")]
                [Headers("X-Request: request-value")]
                Task<string> GetData();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<string> GetData()
                      {
                          var ___route = "data";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              ___request.Headers.Add("X-Client", "client-value");
                              ___request.Headers.Add("X-Request", "request-value");
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    // TODO: Re-enable this test once the generator properly handles header override logic
    // Currently, when both client and request define the same header, both are added.
    // The expected behavior is that request-level headers should override client-level headers.
    /*
    [Fact]
    public async Task Generator_RequestHeaderOverridesClientHeaderCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            [Headers("X-Custom: client-value")]
            public interface ICustomClient
            {
                [Get("data")]
                [Headers("X-Custom: request-value")]
                Task<string> GetData();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                public sealed class CustomClient : ICustomClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public CustomClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> GetData()
                    {
                        var ___route = "data";
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            ___request.Headers.Add("X-Custom", "request-value");
                            using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                            {
                                return await ___response.Content.ReadAsStringAsync().ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
    */
}
