using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Integration;

public class FileClientTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesFileClientCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.IO;
            using System.Threading;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface IFileClient
            {
                [Post("buckets/{bucketId}/files")]
                Task<string> UploadFile([Authorize] string token, string bucketId, [Header("X-Filename")] string filename, [Body] Stream data, CancellationToken cancellationToken);

                [Get("buckets/{bucketId}/files/{fileId}")]
                Task<Stream> DownloadFile(string bucketId, string fileId, CancellationToken cancellationToken);
            }
            """);

        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                  public sealed class FileClient : IFileClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public FileClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public FileClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public FileClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<string> UploadFile(string token, string bucketId, string filename, global::System.IO.Stream data, global::System.Threading.CancellationToken cancellationToken)
                      {
                          var ___route = $"buckets/{(global::System.Web.HttpUtility.UrlPathEncode(bucketId.ToString()))}/files";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                          {
                              ___request.Headers.Add("Authorization", $"Bearer {token}");
                              ___request.Headers.Add("X-Filename", $"{filename}");
                              global::System.Net.Http.HttpContent ___httpContent;
                              using (___httpContent = new global::System.Net.Http.StreamContent(data))
                              {
                                  ___request.Content = ___httpContent;
                                  using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                      return await ___response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                  }
                              }
                          }
                      }

                      public async global::System.Threading.Tasks.Task<global::System.IO.Stream> DownloadFile(string bucketId, string fileId, global::System.Threading.CancellationToken cancellationToken)
                      {
                          var ___route = $"buckets/{(global::System.Web.HttpUtility.UrlPathEncode(bucketId.ToString()))}/files/{(global::System.Web.HttpUtility.UrlPathEncode(fileId.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  return await ___response.Content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false);
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("FileClient.Generated.cs", expectedOutput));
    }
}
