using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Integration;

public class SearchClientTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesSearchClientWithClientHeadersCorrectly()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            [Headers("X-Api-Key: my-api-key")]
            public interface ISearchClient
            {
                [Get("search")]
                Task<string> Search([Query("q")] string keyword, int page, CancellationToken cancellationToken);
            }
            """);

        var expectedOutput = CSharp(
            """
            // <auto-generated/>
            using System.Net.Http.Json;

            namespace X
            {
                [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "0.1.0")]
                public sealed class SearchClient : ISearchClient
                {
                    private readonly global::System.Net.Http.HttpClient ___httpClient;
                    private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                    private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                    public SearchClient(global::System.Net.Http.HttpClient httpClient)
                    {
                        this.___httpClient = httpClient;
                    }

                    public SearchClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonOptions = jsonOptions;
                    }

                    public SearchClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                    {
                        this.___httpClient = httpClient;
                        this.___jsonContext = jsonContext;
                    }

                    public async global::System.Threading.Tasks.Task<string> Search(string keyword, int page, global::System.Threading.CancellationToken cancellationToken)
                    {
                        var ___routeBuilder = new global::System.Text.StringBuilder("search");
                        ___routeBuilder.Append('?');
                        if (keyword is not null) ___routeBuilder.Append($"q={(global::System.Web.HttpUtility.UrlEncode(keyword.ToString()))}&");
                        ___routeBuilder.Append($"page={(global::System.Web.HttpUtility.UrlEncode(page.ToString()))}&");
                        var ___route = ___routeBuilder.ToString(0, ___routeBuilder.Length - 1);
                        using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                        {
                            ___request.Headers.Add("X-Api-Key", "my-api-key");
                            using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                            {
                                ___response.EnsureSuccessStatusCode();
                                return await ___response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                            }
                        }
                    }
                }
            }

            """);

        await TestGenerator(source, ("SearchClient.Generated.cs", expectedOutput));
    }
}
