using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Integration;

public class CrudClientTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesCrudClientCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface IUserClient
            {
                [Get("users/{id}")]
                Task<User> GetUser([Authorize] string token, string id);

                [Post("users")]
                Task<User> CreateUser([Authorize] string token, [Body] User user, CancellationToken cancellationToken);

                [Delete("users/{id}")]
                Task DeleteUser([Authorize] string token, string id, CancellationToken cancellationToken);
            }

            public class User { }
            """);

        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class UserClient : IUserClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public UserClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public UserClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public UserClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<global::X.User> GetUser(string token, string id)
                      {
                          var ___route = $"users/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              ___request.Headers.Add("Authorization", $"Bearer {token}");
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  global::X.User ___deserializedJson;
                                  if (this.___jsonContext is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>().ConfigureAwait(false);
                                  }
                                  return ___deserializedJson;
                              }
                          }
                      }

                      public async global::System.Threading.Tasks.Task<global::X.User> CreateUser(string token, global::X.User user, global::System.Threading.CancellationToken cancellationToken)
                      {
                          var ___route = "users";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                          {
                              ___request.Headers.Add("Authorization", $"Bearer {token}");
                              global::System.Net.Http.HttpContent ___httpContent;
                              if (this.___jsonContext is not null)
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User)));
                              }
                              else
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<global::X.User>(user, options: this.___jsonOptions);
                              }
                              using (___httpContent)
                              {
                                  ___request.Content = ___httpContent;
                                  using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                      global::X.User ___deserializedJson;
                                      if (this.___jsonContext is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::X.User>) this.___jsonContext.GetTypeInfo(typeof(global::X.User)), cancellationToken).ConfigureAwait(false);
                                      }
                                      else if (this.___jsonOptions is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>(this.___jsonOptions, cancellationToken).ConfigureAwait(false);
                                      }
                                      else
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<global::X.User>(cancellationToken).ConfigureAwait(false);
                                      }
                                      return ___deserializedJson;
                                  }
                              }
                          }
                      }

                      public async global::System.Threading.Tasks.Task DeleteUser(string token, string id, global::System.Threading.CancellationToken cancellationToken)
                      {
                          var ___route = $"users/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Delete, ___route))
                          {
                              ___request.Headers.Add("Authorization", $"Bearer {token}");
                              using (var ___response = await this.___httpClient.SendAsync(___request, cancellationToken).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("UserClient.Generated.cs", expectedOutput));
    }
}
