using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Features.Generics;

public class GenericConstraintTests : TestBase
{
    [Fact]
    public async Task Generator_EmitsMethodTypeParameterConstraints()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items/{id}")]
                Task<T> Get<T>(string id) where T : class, new();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<T> Get<T>(string id) where T : class, new()
                      {
                          var ___route = $"items/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  T ___deserializedJson;
                                  if (this.___jsonContext is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>) this.___jsonContext.GetTypeInfo(typeof(T))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>().ConfigureAwait(false);
                                  }
                                  return ___deserializedJson;
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    // Type constraints (as opposed to keyword constraints like class/new()) must be fully
    // global::-qualified: the generated file does not carry the source file's usings, so an
    // unqualified `IEnumerable<int>` (imported via `using System.Collections.Generic;` in the
    // source) would not resolve.
    [Fact]
    public async Task Generator_EmitsGloballyQualifiedTypeConstraints()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;
            using System.Collections.Generic;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items")]
                Task<T> Get<T>() where T : IEnumerable<int>, System.IComparable<T>;
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<T> Get<T>() where T : global::System.Collections.Generic.IEnumerable<int>, global::System.IComparable<T>
                      {
                          var ___route = "items";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  T ___deserializedJson;
                                  if (this.___jsonContext is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>) this.___jsonContext.GetTypeInfo(typeof(T))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>().ConfigureAwait(false);
                                  }
                                  return ___deserializedJson;
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_EmitsInterfaceTypeParameterConstraintsAndBareConstructorNames()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient<T> where T : class, new()
            {
                [Get("items")]
                Task<T> GetAll();
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient<T> : ICustomClient<T> where T : class, new()
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<T> GetAll()
                      {
                          var ___route = "items";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  T ___deserializedJson;
                                  if (this.___jsonContext is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>) this.___jsonContext.GetTypeInfo(typeof(T))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>().ConfigureAwait(false);
                                  }
                                  return ___deserializedJson;
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
