using System.Threading.Tasks;
using Xunit;

namespace TypedHttp.Tests.Features.Generics;

public class GenericMethodTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesGenericMethodWithGenericReturnTypeCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Get("items/{id}")]
                Task<T> Get<T>(string id);
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<T> Get<T>(string id)
                      {
                          var ___route = $"items/{(global::System.Web.HttpUtility.UrlPathEncode(id.ToString()))}";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                          {
                              using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                              {
                                  ___response.EnsureSuccessStatusCode();
                                  T ___deserializedJson;
                                  if (this.___jsonContext is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>) this.___jsonContext.GetTypeInfo(typeof(T))).ConfigureAwait(false);
                                  }
                                  else if (this.___jsonOptions is not null)
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>(this.___jsonOptions).ConfigureAwait(false);
                                  }
                                  else
                                  {
                                      ___deserializedJson = await ___response.Content.ReadFromJsonAsync<T>().ConfigureAwait(false);
                                  }
                                  return ___deserializedJson;
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesGenericMethodWithGenericBodyParameterCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("items")]
                Task Create<T>([Body] T item);
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task Create<T>(T item)
                      {
                          var ___route = "items";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                          {
                              global::System.Net.Http.HttpContent ___httpContent;
                              if (this.___jsonContext is not null)
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<T>(item, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<T>) this.___jsonContext.GetTypeInfo(typeof(T)));
                              }
                              else
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<T>(item, options: this.___jsonOptions);
                              }
                              using (___httpContent)
                              {
                                  ___request.Content = ___httpContent;
                                  using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesGenericMethodWithMultipleTypeParametersCorrectly()
    {
        var source = CSharp(
            """
            using TypedHttp;
            using System.Threading.Tasks;

            namespace X;

            [Client]
            public interface ICustomClient
            {
                [Post("transform")]
                Task<TResult> Transform<TRequest, TResult>([Body] TRequest request);
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  // Generated by TypedHttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                  [global::System.CodeDom.Compiler.GeneratedCode("TypedHttp", "{{ThisVersion.Version}}")]
                  public sealed class CustomClient : ICustomClient
                  {
                      private readonly global::System.Net.Http.HttpClient ___httpClient;
                      private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                      private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                      public CustomClient(global::System.Net.Http.HttpClient httpClient)
                      {
                          this.___httpClient = httpClient;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonOptions = jsonOptions;
                      }

                      public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                      {
                          this.___httpClient = httpClient;
                          this.___jsonContext = jsonContext;
                      }

                      public async global::System.Threading.Tasks.Task<TResult> Transform<TRequest, TResult>(TRequest request)
                      {
                          var ___route = "transform";
                          using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Post, ___route))
                          {
                              global::System.Net.Http.HttpContent ___httpContent;
                              if (this.___jsonContext is not null)
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<TRequest>(request, (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<TRequest>) this.___jsonContext.GetTypeInfo(typeof(TRequest)));
                              }
                              else
                              {
                                  ___httpContent = global::System.Net.Http.Json.JsonContent.Create<TRequest>(request, options: this.___jsonOptions);
                              }
                              using (___httpContent)
                              {
                                  ___request.Content = ___httpContent;
                                  using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                      TResult ___deserializedJson;
                                      if (this.___jsonContext is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<TResult>((global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<TResult>) this.___jsonContext.GetTypeInfo(typeof(TResult))).ConfigureAwait(false);
                                      }
                                      else if (this.___jsonOptions is not null)
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<TResult>(this.___jsonOptions).ConfigureAwait(false);
                                      }
                                      else
                                      {
                                          ___deserializedJson = await ___response.Content.ReadFromJsonAsync<TResult>().ConfigureAwait(false);
                                      }
                                      return ___deserializedJson;
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
