using System.CodeDom.Compiler;
using TypedHttp.Model;

namespace TypedHttp.Emit;

internal sealed class ClientWriter(IndentedTextWriter writer)
{
    public void WriteClient(
        Client            client,
        CancellationToken cancellationToken = default)
    {
        writer.SplitAndWriteLines(
            """
            // <auto-generated/>
            using System.Net.Http.Json;
            """);
        writer.WriteLineNoTabs("");

        // Open every containing scope (namespace and partial types), outermost first.
        var scopes = new Stack<Indentation>();
        foreach (var container in client.Containers)
        {
            cancellationToken.ThrowIfCancellationRequested();
            scopes.Push(writer.Block(container));
        }

        writer.WriteLine($"// Generated by TypedHttp {ThisVersion.Version} released on {ThisVersion.ReleaseDate}");
        writer.WriteLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"TypedHttp\", \"{ThisVersion.Version}\")]");
        using (writer.Block($"{client.Modifiers} sealed class {client.Name} : {client.Interface}{client.ConstraintClauses}"))
        {
            WritePreamble(client.Identifier);

            var requestWriter = new RequestWriter(writer);
            foreach (var request in client.Requests)
            {
                requestWriter.WriteRequest(
                    client.Headers.Array,
                    request,
                    cancellationToken);
            }
        }

        // Close the containing scopes in reverse (innermost first).
        while (scopes.Count > 0)
        {
            cancellationToken.ThrowIfCancellationRequested();
            scopes.Pop().Dispose();
        }
    }

    private void WritePreamble(string name)
    {
        writer.SplitAndWriteLines(
            $"""
             private readonly {Types.HttpClient} {Names.HttpClientField};
             private readonly {Types.JsonSerializerOptions} {Names.JsonOptionsField};
             private readonly {Types.JsonSerializerContext} {Names.JsonContextField};
             """);
        writer.WriteLineNoTabs("");

        using (writer.Block($"public {name}({Types.HttpClient} httpClient)"))
        {
            writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
        }
        writer.WriteLineNoTabs("");

        using (writer.Block($"public {name}({Types.HttpClient} httpClient, {Types.JsonSerializerOptions} jsonOptions)"))
        {
            writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
            writer.WriteLine($"this.{Names.JsonOptionsField} = jsonOptions;");
        }
        writer.WriteLineNoTabs("");

        using (writer.Block($"public {name}({Types.HttpClient} httpClient, {Types.JsonSerializerContext} jsonContext)"))
        {
            writer.WriteLine($"this.{Names.HttpClientField} = httpClient;");
            writer.WriteLine($"this.{Names.JsonContextField} = jsonContext;");
        }
    }
}
