using System.Threading.Tasks;
using Xunit;

namespace Xhttp.Tests.Features.Scoping;

public class ContainingTypeScopingTests : TestBase
{
    [Fact]
    public async Task Generator_GeneratesClientNestedInsidePartialClass()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            public partial class Outer
            {
                [Client]
                public interface ICustomClient
                {
                    [Get("data")]
                    Task GetData();
                }
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  public partial class Outer
                  {
                      // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                      [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                      public sealed class CustomClient : ICustomClient
                      {
                          private readonly global::System.Net.Http.HttpClient ___httpClient;
                          private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                          private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                          public CustomClient(global::System.Net.Http.HttpClient httpClient)
                          {
                              this.___httpClient = httpClient;
                          }

                          public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                          {
                              this.___httpClient = httpClient;
                              this.___jsonOptions = jsonOptions;
                          }

                          public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                          {
                              this.___httpClient = httpClient;
                              this.___jsonContext = jsonContext;
                          }

                          public async global::System.Threading.Tasks.Task GetData()
                          {
                              var ___route = "data";
                              using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                              {
                                  using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesClientNestedInsidePartialStruct()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            public partial struct Outer
            {
                [Client]
                public interface ICustomClient
                {
                    [Get("data")]
                    Task GetData();
                }
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  public partial struct Outer
                  {
                      // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                      [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                      public sealed class CustomClient : ICustomClient
                      {
                          private readonly global::System.Net.Http.HttpClient ___httpClient;
                          private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                          private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                          public CustomClient(global::System.Net.Http.HttpClient httpClient)
                          {
                              this.___httpClient = httpClient;
                          }

                          public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                          {
                              this.___httpClient = httpClient;
                              this.___jsonOptions = jsonOptions;
                          }

                          public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                          {
                              this.___httpClient = httpClient;
                              this.___jsonContext = jsonContext;
                          }

                          public async global::System.Threading.Tasks.Task GetData()
                          {
                              var ___route = "data";
                              using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                              {
                                  using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                  {
                                      ___response.EnsureSuccessStatusCode();
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }

    [Fact]
    public async Task Generator_GeneratesClientDeeplyNested()
    {
        var source = CSharp(
            """
            using Xhttp;
            using System.Threading.Tasks;

            namespace X;

            public partial class Outer
            {
                public partial class Inner
                {
                    [Client]
                    public interface ICustomClient
                    {
                        [Get("data")]
                        Task GetData();
                    }
                }
            }
            """);
        var expectedOutput = CSharp(
            $$"""
              // <auto-generated/>
              using System.Net.Http.Json;

              namespace X
              {
                  public partial class Outer
                  {
                      public partial class Inner
                      {
                          // Generated by xhttp {{ThisVersion.Version}} released on {{ThisVersion.ReleaseDate}}
                          [global::System.CodeDom.Compiler.GeneratedCode("Xhttp", "{{ThisVersion.Version}}")]
                          public sealed class CustomClient : ICustomClient
                          {
                              private readonly global::System.Net.Http.HttpClient ___httpClient;
                              private readonly global::System.Text.Json.JsonSerializerOptions ___jsonOptions;
                              private readonly global::System.Text.Json.Serialization.JsonSerializerContext ___jsonContext;

                              public CustomClient(global::System.Net.Http.HttpClient httpClient)
                              {
                                  this.___httpClient = httpClient;
                              }

                              public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.JsonSerializerOptions jsonOptions)
                              {
                                  this.___httpClient = httpClient;
                                  this.___jsonOptions = jsonOptions;
                              }

                              public CustomClient(global::System.Net.Http.HttpClient httpClient, global::System.Text.Json.Serialization.JsonSerializerContext jsonContext)
                              {
                                  this.___httpClient = httpClient;
                                  this.___jsonContext = jsonContext;
                              }

                              public async global::System.Threading.Tasks.Task GetData()
                              {
                                  var ___route = "data";
                                  using (var ___request = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, ___route))
                                  {
                                      using (var ___response = await this.___httpClient.SendAsync(___request).ConfigureAwait(false))
                                      {
                                          ___response.EnsureSuccessStatusCode();
                                      }
                                  }
                              }
                          }
                      }
                  }
              }

              """);

        await TestGenerator(source, ("CustomClient.Generated.cs", expectedOutput));
    }
}
