on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed for release-please to update files and create releases
  issues: write
  pull-requests: write # Needed for release-please to create PRs
  id-token: write # NuGet/login

name: Release Please and Publish

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      # The logic below handles the NuGet publication:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Install .NET SDKs
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x
        if: ${{ steps.release.outputs.release_created }}
      - name: Package Libraries
        run: |
          dotnet pack src/TypedHttp/ \
            --configuration Release \
            --output ./packages \
            --include-symbols
        if: ${{ steps.release.outputs.release_created }}
      - name: Get a short-lived NuGet API key
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish Packages to NuGet
        run: |
          dotnet nuget push ./packages/*.nupkg \
            --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifacts
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
